"""
@ProjectName: DataAnalysis
@FileName：track_global_info.py
@IDE：PyCharm
@Author：Libre
@Time：2024/8/15 下午2:39
"""
global_json = {
    "country": [
        {
            "key": "AC",
            "_countryCode": "247",
            "_firstCode": "A",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "ASSD",
            "_name": "阿森松岛 [GB]",
            "_nameGeo": "",
            "_numberKey": "9003"
        },
        {
            "key": "AD",
            "_countryCode": "376",
            "_firstCode": "A",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "ADE",
            "_name": "安道尔",
            "_nameGeo": "Andorra",
            "_numberKey": "0105"
        },
        {
            "key": "AE",
            "_countryCode": "971",
            "_firstCode": "A",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "ALQ",
            "_name": "阿联酋",
            "_nameGeo": "United Arab Emirates",
            "_numberKey": "0503"
        },
        {
            "key": "AF",
            "_countryCode": "93",
            "_firstCode": "A",
            "_gArea": "22",
            "_gContinent": "2",
            "_mnemonic": "AFH",
            "_name": "阿富汗",
            "_nameGeo": "Afghanistan",
            "_numberKey": "0102"
        },
        {
            "key": "AG",
            "_countryCode": "1-268",
            "_firstCode": "A",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "ADGHBBD",
            "_name": "安提瓜和巴布达",
            "_nameGeo": "Antigua and Barb.",
            "_numberKey": "0110"
        },
        {
            "key": "AI",
            "_countryCode": "1-264",
            "_firstCode": "A",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "AGL",
            "_name": "安圭拉 [GB]",
            "_nameGeo": "",
            "_numberKey": "9002"
        },
        {
            "key": "AL",
            "_countryCode": "355",
            "_firstCode": "A",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "AEBNY",
            "_name": "阿尔巴尼亚",
            "_nameGeo": "Albania",
            "_numberKey": "0103"
        },
        {
            "key": "AM",
            "_countryCode": "374",
            "_firstCode": "Y",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "YMNY",
            "_name": "亚美尼亚",
            "_nameGeo": "Armenia",
            "_numberKey": "0113"
        },
        {
            "key": "AN",
            "_countryCode": "599",
            "_firstCode": "H",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "HSADLS",
            "_name": "荷属安的列斯 [NL]",
            "_nameGeo": "",
            "_numberKey": "9202"
        },
        {
            "key": "AO",
            "_countryCode": "244",
            "_firstCode": "A",
            "_gArea": "33",
            "_gContinent": "3",
            "_mnemonic": "AGL",
            "_name": "安哥拉",
            "_nameGeo": "Angola",
            "_numberKey": "0106"
        },
        {
            "key": "AQ",
            "_countryCode": "672",
            "_firstCode": "N",
            "_gArea": "51",
            "_gContinent": "5",
            "_mnemonic": "NJZ",
            "_name": "南极洲",
            "_nameGeo": "",
            "_numberKey": "0108"
        },
        {
            "key": "AR",
            "_countryCode": "54",
            "_firstCode": "A",
            "_gArea": "03",
            "_gContinent": "0",
            "_mnemonic": "AGT",
            "_name": "阿根廷",
            "_nameGeo": "Argentina",
            "_numberKey": "0112"
        },
        {
            "key": "AT",
            "_countryCode": "43",
            "_firstCode": "A",
            "_gArea": "13",
            "_gContinent": "1",
            "_mnemonic": "ADL",
            "_name": "奥地利",
            "_nameGeo": "Austria",
            "_numberKey": "0116"
        },
        {
            "key": "AU",
            "_countryCode": "61",
            "_firstCode": "A",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "ADLY",
            "_name": "澳大利亚",
            "_nameGeo": "Australia",
            "_numberKey": "0115"
        },
        {
            "key": "AW",
            "_countryCode": "297",
            "_firstCode": "A",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "ALB",
            "_name": "阿鲁巴 [NL]",
            "_nameGeo": "",
            "_numberKey": "9203"
        },
        {
            "key": "AX",
            "_countryCode": "3-5818",
            "_firstCode": "A",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "ALQD",
            "_name": "奥兰群岛 [FI]",
            "_nameGeo": "Aland",
            "_numberKey": "9102"
        },
        {
            "key": "AZ",
            "_countryCode": "994",
            "_firstCode": "A",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "ASBJ",
            "_name": "阿塞拜疆",
            "_nameGeo": "Azerbaijan",
            "_numberKey": "0117"
        },
        {
            "key": "BA",
            "_countryCode": "387",
            "_firstCode": "B",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "BH",
            "_name": "波黑",
            "_nameGeo": "Bosnia and Herz.",
            "_numberKey": "0212"
        },
        {
            "key": "BB",
            "_countryCode": "1-246",
            "_firstCode": "B",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "BBDS",
            "_name": "巴巴多斯",
            "_nameGeo": "Barbados",
            "_numberKey": "0204"
        },
        {
            "key": "BD",
            "_countryCode": "880",
            "_firstCode": "M",
            "_gArea": "22",
            "_gContinent": "2",
            "_mnemonic": "MJLG",
            "_name": "孟加拉国",
            "_nameGeo": "Bangladesh",
            "_numberKey": "0203"
        },
        {
            "key": "BE",
            "_countryCode": "32",
            "_firstCode": "B",
            "_gArea": "13",
            "_gContinent": "1",
            "_mnemonic": "BLS",
            "_name": "比利时",
            "_nameGeo": "Belgium",
            "_numberKey": "0206"
        },
        {
            "key": "BF",
            "_countryCode": "226",
            "_firstCode": "B",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "BJNFS",
            "_name": "布基纳法索",
            "_nameGeo": "Burkina Faso",
            "_numberKey": "0218"
        },
        {
            "key": "BG",
            "_countryCode": "359",
            "_firstCode": "B",
            "_gArea": "11",
            "_gContinent": "1",
            "_mnemonic": "BJLY",
            "_name": "保加利亚",
            "_nameGeo": "Bulgaria",
            "_numberKey": "0217"
        },
        {
            "key": "BH",
            "_countryCode": "973",
            "_firstCode": "B",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "BL",
            "_name": "巴林",
            "_nameGeo": "Bahrain",
            "_numberKey": "0202"
        },
        {
            "key": "BI",
            "_countryCode": "257",
            "_firstCode": "B",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "BLD",
            "_name": "布隆迪",
            "_nameGeo": "Burundi",
            "_numberKey": "0219"
        },
        {
            "key": "BJ",
            "_countryCode": "229",
            "_firstCode": "B",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "BN",
            "_name": "贝宁",
            "_nameGeo": "Benin",
            "_numberKey": "0208"
        },
        {
            "key": "BM",
            "_countryCode": "1-441",
            "_firstCode": "B",
            "_gArea": "00",
            "_gContinent": "0",
            "_mnemonic": "BMD",
            "_name": "百慕大 [GB]",
            "_nameGeo": "Bermuda",
            "_numberKey": "9004"
        },
        {
            "key": "BN",
            "_countryCode": "673",
            "_firstCode": "W",
            "_gArea": "23",
            "_gContinent": "2",
            "_mnemonic": "WL",
            "_name": "文莱",
            "_nameGeo": "Brunei",
            "_numberKey": "0216"
        },
        {
            "key": "BO",
            "_countryCode": "591",
            "_firstCode": "B",
            "_gArea": "03",
            "_gContinent": "0",
            "_mnemonic": "BLWY",
            "_name": "玻利维亚",
            "_nameGeo": "Bolivia",
            "_numberKey": "0211"
        },
        {
            "key": "BR",
            "_countryCode": "55",
            "_firstCode": "B",
            "_gArea": "03",
            "_gContinent": "0",
            "_mnemonic": "BX",
            "_name": "巴西",
            "_nameGeo": "Brazil",
            "_numberKey": "0215"
        },
        {
            "key": "BS",
            "_countryCode": "1-242",
            "_firstCode": "B",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "BHM",
            "_name": "巴哈马",
            "_nameGeo": "Bahamas",
            "_numberKey": "0201"
        },
        {
            "key": "BT",
            "_countryCode": "975",
            "_firstCode": "B",
            "_gArea": "22",
            "_gContinent": "2",
            "_mnemonic": "BD",
            "_name": "不丹",
            "_nameGeo": "Bhutan",
            "_numberKey": "0210"
        },
        {
            "key": "BW",
            "_countryCode": "267",
            "_firstCode": "B",
            "_gArea": "32",
            "_gContinent": "3",
            "_mnemonic": "BCWN",
            "_name": "博茨瓦纳",
            "_nameGeo": "Botswana",
            "_numberKey": "0213"
        },
        {
            "key": "BY",
            "_countryCode": "375",
            "_firstCode": "B",
            "_gArea": "11",
            "_gContinent": "1",
            "_mnemonic": "BELS",
            "_name": "白俄罗斯",
            "_nameGeo": "Belarus",
            "_numberKey": "0205"
        },
        {
            "key": "BZ",
            "_countryCode": "501",
            "_firstCode": "B",
            "_gArea": "01",
            "_gContinent": "0",
            "_mnemonic": "BLC",
            "_name": "伯利兹",
            "_nameGeo": "Belize",
            "_numberKey": "0207"
        },
        {
            "key": "CA",
            "_countryCode": "1",
            "_firstCode": "J",
            "_gArea": "00",
            "_gContinent": "0",
            "_mnemonic": "JND",
            "_name": "加拿大",
            "_nameGeo": "Canada",
            "_numberKey": "0304"
        },
        {
            "key": "CD",
            "_countryCode": "243",
            "_firstCode": "G",
            "_gArea": "33",
            "_gContinent": "3",
            "_mnemonic": "GGMZGHG",
            "_name": "刚果民主共和国",
            "_nameGeo": "Dem. Rep. Congo",
            "_numberKey": "0316"
        },
        {
            "key": "CF",
            "_countryCode": "236",
            "_firstCode": "Z",
            "_gArea": "33",
            "_gContinent": "3",
            "_mnemonic": "ZFGHG",
            "_name": "中非共和国",
            "_nameGeo": "Central African Rep.",
            "_numberKey": "0308"
        },
        {
            "key": "CG",
            "_countryCode": "242",
            "_firstCode": "G",
            "_gArea": "33",
            "_gContinent": "3",
            "_mnemonic": "GGGHG",
            "_name": "刚果共和国",
            "_nameGeo": "Congo",
            "_numberKey": "0315"
        },
        {
            "key": "CH",
            "_countryCode": "41",
            "_firstCode": "R",
            "_gArea": "13",
            "_gContinent": "1",
            "_mnemonic": "RS",
            "_name": "瑞士",
            "_nameGeo": "Switzerland",
            "_numberKey": "1925"
        },
        {
            "key": "CI",
            "_countryCode": "225",
            "_firstCode": "K",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "KTDW",
            "_name": "科特迪瓦",
            "_nameGeo": "Côte d'Ivoire",
            "_numberKey": "0312"
        },
        {
            "key": "CK",
            "_countryCode": "682",
            "_firstCode": "K",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "KKQD",
            "_name": "库克群岛 [NZ]",
            "_nameGeo": "",
            "_numberKey": "0317"
        },
        {
            "key": "CL",
            "_countryCode": "56",
            "_firstCode": "Z",
            "_gArea": "03",
            "_gContinent": "0",
            "_mnemonic": "ZL",
            "_name": "智利",
            "_nameGeo": "Chile",
            "_numberKey": "0310"
        },
        {
            "key": "CM",
            "_countryCode": "237",
            "_firstCode": "K",
            "_gArea": "33",
            "_gContinent": "3",
            "_mnemonic": "KML",
            "_name": "喀麦隆",
            "_nameGeo": "Cameroon",
            "_numberKey": "0303"
        },
        {
            "key": "CN",
            "_countryCode": "86",
            "_firstCode": "Z",
            "_gArea": "21",
            "_gContinent": "2",
            "_mnemonic": "ZG",
            "_name": "中国",
            "_nameGeo": "China",
            "_numberKey": "0301"
        },
        {
            "key": "CO",
            "_countryCode": "57",
            "_firstCode": "G",
            "_gArea": "03",
            "_gContinent": "0",
            "_mnemonic": "GLBY",
            "_name": "哥伦比亚",
            "_nameGeo": "Colombia",
            "_numberKey": "0313"
        },
        {
            "key": "CR",
            "_countryCode": "506",
            "_firstCode": "G",
            "_gArea": "01",
            "_gContinent": "0",
            "_mnemonic": "GSDLJ",
            "_name": "哥斯达黎加",
            "_nameGeo": "Costa Rica",
            "_numberKey": "0318"
        },
        {
            "key": "CU",
            "_countryCode": "53",
            "_firstCode": "G",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "GB",
            "_name": "古巴",
            "_nameGeo": "Cuba",
            "_numberKey": "0320"
        },
        {
            "key": "CV",
            "_countryCode": "238",
            "_firstCode": "F",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "FDJ",
            "_name": "佛得角",
            "_nameGeo": "Cape Verde",
            "_numberKey": "0306"
        },
        {
            "key": "CY",
            "_countryCode": "357",
            "_firstCode": "S",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "SPLS",
            "_name": "塞浦路斯",
            "_nameGeo": "Cyprus",
            "_numberKey": "0321"
        },
        {
            "key": "CZ",
            "_countryCode": "420",
            "_firstCode": "J",
            "_gArea": "11",
            "_gContinent": "1",
            "_mnemonic": "JK",
            "_name": "捷克",
            "_nameGeo": "Czech Rep.",
            "_numberKey": "0322"
        },
        {
            "key": "DE",
            "_countryCode": "49",
            "_firstCode": "D",
            "_gArea": "13",
            "_gContinent": "1",
            "_mnemonic": "DG",
            "_name": "德国",
            "_nameGeo": "Germany",
            "_numberKey": "0704"
        },
        {
            "key": "DJ",
            "_countryCode": "253",
            "_firstCode": "J",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "JBD",
            "_name": "吉布提",
            "_nameGeo": "Djibouti",
            "_numberKey": "0402"
        },
        {
            "key": "DK",
            "_countryCode": "45",
            "_firstCode": "D",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "DM",
            "_name": "丹麦",
            "_nameGeo": "Denmark",
            "_numberKey": "0401"
        },
        {
            "key": "DM",
            "_countryCode": "1-767",
            "_firstCode": "D",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "DMNK",
            "_name": "多米尼克",
            "_nameGeo": "Dominica",
            "_numberKey": "0403"
        },
        {
            "key": "DO",
            "_countryCode": "1-809",
            "_firstCode": "D",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "DMNJ",
            "_name": "多米尼加",
            "_nameGeo": "Dominican Rep.",
            "_numberKey": "0404"
        },
        {
            "key": "DZ",
            "_countryCode": "213",
            "_firstCode": "A",
            "_gArea": "35",
            "_gContinent": "3",
            "_mnemonic": "AEJLY",
            "_name": "阿尔及利亚",
            "_nameGeo": "Algeria",
            "_numberKey": "0104"
        },
        {
            "key": "EC",
            "_countryCode": "593",
            "_firstCode": "E",
            "_gArea": "03",
            "_gContinent": "0",
            "_mnemonic": "EGDE",
            "_name": "厄瓜多尔",
            "_nameGeo": "Ecuador",
            "_numberKey": "0501"
        },
        {
            "key": "EE",
            "_countryCode": "372",
            "_firstCode": "A",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "ASNY",
            "_name": "爱沙尼亚",
            "_nameGeo": "Estonia",
            "_numberKey": "0504"
        },
        {
            "key": "EG",
            "_countryCode": "20",
            "_firstCode": "A",
            "_gArea": "35",
            "_gContinent": "3",
            "_mnemonic": "AJ",
            "_name": "埃及",
            "_nameGeo": "Egypt",
            "_numberKey": "0502"
        },
        {
            "key": "EH",
            "_countryCode": "212",
            "_firstCode": "X",
            "_gArea": "35",
            "_gContinent": "3",
            "_mnemonic": "XSHL",
            "_name": "西撒哈拉",
            "_nameGeo": "W. Sahara",
            "_numberKey": "2302"
        },
        {
            "key": "ER",
            "_countryCode": "291",
            "_firstCode": "E",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "ELTLY",
            "_name": "厄立特里亚",
            "_nameGeo": "Eritrea",
            "_numberKey": "0506"
        },
        {
            "key": "ES",
            "_countryCode": "34",
            "_firstCode": "X",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "XBY",
            "_name": "西班牙",
            "_nameGeo": "Spain",
            "_numberKey": "1918"
        },
        {
            "key": "ET",
            "_countryCode": "251",
            "_firstCode": "A",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "ASEBY",
            "_name": "埃塞俄比亚",
            "_nameGeo": "Ethiopia",
            "_numberKey": "0505"
        },
        {
            "key": "FI",
            "_countryCode": "358",
            "_firstCode": "F",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "FL",
            "_name": "芬兰",
            "_nameGeo": "Finland",
            "_numberKey": "0604"
        },
        {
            "key": "FJ",
            "_countryCode": "679",
            "_firstCode": "F",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "FJ",
            "_name": "斐济",
            "_nameGeo": "Fiji",
            "_numberKey": "0603"
        },
        {
            "key": "FM",
            "_countryCode": "691",
            "_firstCode": "M",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "MKLNXYLB",
            "_name": "密克罗尼西亚联邦",
            "_nameGeo": "Micronesia",
            "_numberKey": "1315"
        },
        {
            "key": "FO",
            "_countryCode": "298",
            "_firstCode": "F",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "FLQD",
            "_name": "法罗群岛 [DK]",
            "_nameGeo": "",
            "_numberKey": "9602"
        },
        {
            "key": "FR",
            "_countryCode": "33",
            "_firstCode": "F",
            "_gArea": "13",
            "_gContinent": "1",
            "_mnemonic": "FG",
            "_name": "法国",
            "_nameGeo": "France",
            "_numberKey": "0605"
        },
        {
            "key": "GA",
            "_countryCode": "241",
            "_firstCode": "J",
            "_gArea": "33",
            "_gContinent": "3",
            "_mnemonic": "JP",
            "_name": "加蓬",
            "_nameGeo": "Gabon",
            "_numberKey": "0701"
        },
        {
            "key": "GB",
            "_countryCode": "44",
            "_firstCode": "Y",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "YG",
            "_name": "英国",
            "_nameGeo": "United Kingdom",
            "_numberKey": "1103"
        },
        {
            "key": "GD",
            "_countryCode": "1-473",
            "_firstCode": "G",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "GLND",
            "_name": "格林纳达 [GB]",
            "_nameGeo": "Grenada",
            "_numberKey": "0709"
        },
        {
            "key": "GE",
            "_countryCode": "995",
            "_firstCode": "G",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "GLJY",
            "_name": "格鲁吉亚",
            "_nameGeo": "Georgia",
            "_numberKey": "0703"
        },
        {
            "key": "GG",
            "_countryCode": "44-1481",
            "_firstCode": "G",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "GXD",
            "_name": "根西岛 [GB]",
            "_nameGeo": "",
            "_numberKey": "9007"
        },
        {
            "key": "GH",
            "_countryCode": "233",
            "_firstCode": "J",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "JN",
            "_name": "加纳",
            "_nameGeo": "Ghana",
            "_numberKey": "0705"
        },
        {
            "key": "GI",
            "_countryCode": "350",
            "_firstCode": "Z",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "ZBLT",
            "_name": "直布罗陀 [GB]",
            "_nameGeo": "",
            "_numberKey": "9006"
        },
        {
            "key": "GL",
            "_countryCode": "299",
            "_firstCode": "G",
            "_gArea": "00",
            "_gContinent": "0",
            "_mnemonic": "GLL",
            "_name": "格陵兰 [DK]",
            "_nameGeo": "Greenland",
            "_numberKey": "9603"
        },
        {
            "key": "GM",
            "_countryCode": "220",
            "_firstCode": "G",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "GBY",
            "_name": "冈比亚",
            "_nameGeo": "Gambia",
            "_numberKey": "0702"
        },
        {
            "key": "GN",
            "_countryCode": "224",
            "_firstCode": "J",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "JNYGHG",
            "_name": "几内亚共和国",
            "_nameGeo": "Guinea",
            "_numberKey": "0713"
        },
        {
            "key": "GQ",
            "_countryCode": "240",
            "_firstCode": "C",
            "_gArea": "33",
            "_gContinent": "3",
            "_mnemonic": "CDJNY",
            "_name": "赤道几内亚",
            "_nameGeo": "Eq. Guinea",
            "_numberKey": "0507"
        },
        {
            "key": "GR",
            "_countryCode": "30",
            "_firstCode": "X",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "XL",
            "_name": "希腊",
            "_nameGeo": "Greece",
            "_numberKey": "0707"
        },
        {
            "key": "GT",
            "_countryCode": "502",
            "_firstCode": "W",
            "_gArea": "01",
            "_gContinent": "0",
            "_mnemonic": "WDML",
            "_name": "危地马拉",
            "_nameGeo": "Guatemala",
            "_numberKey": "0712"
        },
        {
            "key": "GW",
            "_countryCode": "245",
            "_firstCode": "J",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "JNYBS",
            "_name": "几内亚比绍",
            "_nameGeo": "Guinea-Bissau",
            "_numberKey": "0716"
        },
        {
            "key": "GY",
            "_countryCode": "592",
            "_firstCode": "G",
            "_gArea": "03",
            "_gContinent": "0",
            "_mnemonic": "GYN",
            "_name": "圭亚那",
            "_nameGeo": "Guyana",
            "_numberKey": "0714"
        },
        {
            "key": "HK",
            "_countryCode": "852",
            "_firstCode": "X",
            "_gArea": "21",
            "_gContinent": "2",
            "_mnemonic": "XG",
            "_name": "香港 [CN]",
            "_nameGeo": "",
            "_numberKey": "0801"
        },
        {
            "key": "HN",
            "_countryCode": "504",
            "_firstCode": "H",
            "_gArea": "01",
            "_gContinent": "0",
            "_mnemonic": "HDLS",
            "_name": "洪都拉斯",
            "_nameGeo": "Honduras",
            "_numberKey": "0804"
        },
        {
            "key": "HR",
            "_countryCode": "385",
            "_firstCode": "K",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "KLDY",
            "_name": "克罗地亚",
            "_nameGeo": "Croatia",
            "_numberKey": "0319"
        },
        {
            "key": "HT",
            "_countryCode": "509",
            "_firstCode": "H",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "HD",
            "_name": "海地",
            "_nameGeo": "Haiti",
            "_numberKey": "0802"
        },
        {
            "key": "HU",
            "_countryCode": "36",
            "_firstCode": "X",
            "_gArea": "11",
            "_gContinent": "1",
            "_mnemonic": "XYL",
            "_name": "匈牙利",
            "_nameGeo": "Hungary",
            "_numberKey": "0805"
        },
        {
            "key": "ID",
            "_countryCode": "62",
            "_firstCode": "Y",
            "_gArea": "23",
            "_gContinent": "2",
            "_mnemonic": "YDNXY",
            "_name": "印度尼西亚",
            "_nameGeo": "Indonesia",
            "_numberKey": "0903"
        },
        {
            "key": "IE",
            "_countryCode": "353",
            "_firstCode": "A",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "AEL",
            "_name": "爱尔兰",
            "_nameGeo": "Ireland",
            "_numberKey": "0905"
        },
        {
            "key": "IL",
            "_countryCode": "972",
            "_firstCode": "Y",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "YSL",
            "_name": "以色列",
            "_nameGeo": "Israel",
            "_numberKey": "0906"
        },
        {
            "key": "IN",
            "_countryCode": "91",
            "_firstCode": "Y",
            "_gArea": "22",
            "_gContinent": "2",
            "_mnemonic": "YD",
            "_name": "印度",
            "_nameGeo": "India",
            "_numberKey": "0902"
        },
        {
            "key": "IQ",
            "_countryCode": "964",
            "_firstCode": "Y",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "YLK",
            "_name": "伊拉克",
            "_nameGeo": "Iraq",
            "_numberKey": "0908"
        },
        {
            "key": "IR",
            "_countryCode": "98",
            "_firstCode": "Y",
            "_gArea": "22",
            "_gContinent": "2",
            "_mnemonic": "YL",
            "_name": "伊朗",
            "_nameGeo": "Iran",
            "_numberKey": "0904"
        },
        {
            "key": "IS",
            "_countryCode": "354",
            "_firstCode": "B",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "BD",
            "_name": "冰岛",
            "_nameGeo": "Iceland",
            "_numberKey": "0901"
        },
        {
            "key": "IT",
            "_countryCode": "39",
            "_firstCode": "Y",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "YDL",
            "_name": "意大利",
            "_nameGeo": "Italy",
            "_numberKey": "0907"
        },
        {
            "key": "JE",
            "_countryCode": "44-1534",
            "_firstCode": "Z",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "ZXD",
            "_name": "泽西岛[GB]",
            "_nameGeo": "Jersey",
            "_numberKey": "9009"
        },
        {
            "key": "JM",
            "_countryCode": "1-876",
            "_firstCode": "Y",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "YMJ",
            "_name": "牙买加",
            "_nameGeo": "Jamaica",
            "_numberKey": "1001"
        },
        {
            "key": "JO",
            "_countryCode": "962",
            "_firstCode": "Y",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "YD",
            "_name": "约旦",
            "_nameGeo": "Jordan",
            "_numberKey": "1003"
        },
        {
            "key": "JP",
            "_countryCode": "81",
            "_firstCode": "R",
            "_gArea": "21",
            "_gContinent": "2",
            "_mnemonic": "RB",
            "_name": "日本",
            "_nameGeo": "Japan",
            "_numberKey": "1002"
        },
        {
            "key": "KE",
            "_countryCode": "254",
            "_firstCode": "K",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "KNY",
            "_name": "肯尼亚",
            "_nameGeo": "Kenya",
            "_numberKey": "1102"
        },
        {
            "key": "KG",
            "_countryCode": "996",
            "_firstCode": "J",
            "_gArea": "24",
            "_gContinent": "2",
            "_mnemonic": "JEJSST",
            "_name": "吉尔吉斯斯坦",
            "_nameGeo": "Kyrgyzstan",
            "_numberKey": "1109"
        },
        {
            "key": "KH",
            "_countryCode": "855",
            "_firstCode": "J",
            "_gArea": "23",
            "_gContinent": "2",
            "_mnemonic": "JBZ",
            "_name": "柬埔寨",
            "_nameGeo": "Cambodia",
            "_numberKey": "0302"
        },
        {
            "key": "KI",
            "_countryCode": "686",
            "_firstCode": "J",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "JLBS",
            "_name": "基里巴斯",
            "_nameGeo": "Kiribati",
            "_numberKey": "1104"
        },
        {
            "key": "KM",
            "_countryCode": "269",
            "_firstCode": "K",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "KML",
            "_name": "科摩罗",
            "_nameGeo": "Comoros",
            "_numberKey": "0314"
        },
        {
            "key": "KN",
            "_countryCode": "1-869",
            "_firstCode": "S",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "SJCHNWS",
            "_name": "圣基茨和尼维斯",
            "_nameGeo": "",
            "_numberKey": "1927"
        },
        {
            "key": "KP",
            "_countryCode": "850",
            "_firstCode": "C",
            "_gArea": "21",
            "_gContinent": "2",
            "_mnemonic": "CX",
            "_name": "朝鲜",
            "_nameGeo": "Dem. Rep. Korea",
            "_numberKey": "1106"
        },
        {
            "key": "KR",
            "_countryCode": "82",
            "_firstCode": "H",
            "_gArea": "21",
            "_gContinent": "2",
            "_mnemonic": "HG",
            "_name": "韩国",
            "_nameGeo": "Korea",
            "_numberKey": "1105"
        },
        {
            "key": "KW",
            "_countryCode": "965",
            "_firstCode": "K",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "KWT",
            "_name": "科威特",
            "_nameGeo": "Kuwait",
            "_numberKey": "1108"
        },
        {
            "key": "KY",
            "_countryCode": "1-345",
            "_firstCode": "K",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "KMQD",
            "_name": "开曼群岛 [GB]",
            "_nameGeo": "Cayman Is.",
            "_numberKey": "9005"
        },
        {
            "key": "KZ",
            "_countryCode": "7",
            "_firstCode": "H",
            "_gArea": "24",
            "_gContinent": "2",
            "_mnemonic": "HSKST",
            "_name": "哈萨克斯坦",
            "_nameGeo": "Kazakhstan",
            "_numberKey": "1101"
        },
        {
            "key": "LA",
            "_countryCode": "856",
            "_firstCode": "L",
            "_gArea": "23",
            "_gContinent": "2",
            "_mnemonic": "LW",
            "_name": "老挝",
            "_nameGeo": "Lao PDR",
            "_numberKey": "1201"
        },
        {
            "key": "LB",
            "_countryCode": "961",
            "_firstCode": "L",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "LBN",
            "_name": "黎巴嫩",
            "_nameGeo": "Lebanon",
            "_numberKey": "1203"
        },
        {
            "key": "LC",
            "_countryCode": "1-758",
            "_firstCode": "S",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "SLXY",
            "_name": "圣卢西亚",
            "_nameGeo": "Saint Lucia",
            "_numberKey": "1209"
        },
        {
            "key": "LI",
            "_countryCode": "423",
            "_firstCode": "L",
            "_gArea": "13",
            "_gContinent": "1",
            "_mnemonic": "LZDSD",
            "_name": "列支敦士登",
            "_nameGeo": "Liechtenstein",
            "_numberKey": "1207"
        },
        {
            "key": "LK",
            "_countryCode": "94",
            "_firstCode": "S",
            "_gArea": "22",
            "_gContinent": "2",
            "_mnemonic": "SLLK",
            "_name": "斯里兰卡",
            "_nameGeo": "Sri Lanka",
            "_numberKey": "1919"
        },
        {
            "key": "LR",
            "_countryCode": "231",
            "_firstCode": "L",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "LBLY",
            "_name": "利比里亚",
            "_nameGeo": "Liberia",
            "_numberKey": "1205"
        },
        {
            "key": "LS",
            "_countryCode": "266",
            "_firstCode": "L",
            "_gArea": "32",
            "_gContinent": "3",
            "_mnemonic": "LST",
            "_name": "莱索托",
            "_nameGeo": "Lesotho",
            "_numberKey": "1204"
        },
        {
            "key": "LT",
            "_countryCode": "370",
            "_firstCode": "L",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "LTW",
            "_name": "立陶宛",
            "_nameGeo": "Lithuania",
            "_numberKey": "1208"
        },
        {
            "key": "LU",
            "_countryCode": "352",
            "_firstCode": "L",
            "_gArea": "13",
            "_gContinent": "1",
            "_mnemonic": "LSB",
            "_name": "卢森堡",
            "_nameGeo": "Luxembourg",
            "_numberKey": "1210"
        },
        {
            "key": "LV",
            "_countryCode": "371",
            "_firstCode": "L",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "LTWY",
            "_name": "拉脱维亚",
            "_nameGeo": "Latvia",
            "_numberKey": "1202"
        },
        {
            "key": "LY",
            "_countryCode": "218",
            "_firstCode": "L",
            "_gArea": "35",
            "_gContinent": "3",
            "_mnemonic": "LBY",
            "_name": "利比亚",
            "_nameGeo": "Libya",
            "_numberKey": "1206"
        },
        {
            "key": "MA",
            "_countryCode": "212",
            "_firstCode": "M",
            "_gArea": "35",
            "_gContinent": "3",
            "_mnemonic": "MLG",
            "_name": "摩洛哥",
            "_nameGeo": "Morocco",
            "_numberKey": "1321"
        },
        {
            "key": "MC",
            "_countryCode": "377",
            "_firstCode": "M",
            "_gArea": "13",
            "_gContinent": "1",
            "_mnemonic": "MNG",
            "_name": "摩纳哥",
            "_nameGeo": "",
            "_numberKey": "1317"
        },
        {
            "key": "MD",
            "_countryCode": "373",
            "_firstCode": "M",
            "_gArea": "11",
            "_gContinent": "1",
            "_mnemonic": "MEDW",
            "_name": "摩尔多瓦",
            "_nameGeo": "Moldova",
            "_numberKey": "1316"
        },
        {
            "key": "ME",
            "_countryCode": "382",
            "_firstCode": "H",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "HS",
            "_name": "黑山",
            "_nameGeo": "Montenegro",
            "_numberKey": "1319"
        },
        {
            "key": "MG",
            "_countryCode": "261",
            "_firstCode": "M",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "MDJSJ",
            "_name": "马达加斯加",
            "_nameGeo": "Madagascar",
            "_numberKey": "1303"
        },
        {
            "key": "MH",
            "_countryCode": "692",
            "_firstCode": "M",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "MSEQD",
            "_name": "马绍尔群岛",
            "_nameGeo": "",
            "_numberKey": "1310"
        },
        {
            "key": "MK",
            "_countryCode": "389",
            "_firstCode": "M",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "MJD",
            "_name": "马其顿",
            "_nameGeo": "Macedonia",
            "_numberKey": "1302"
        },
        {
            "key": "ML",
            "_countryCode": "223",
            "_firstCode": "M",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "MLGHG",
            "_name": "马里共和国",
            "_nameGeo": "Mali",
            "_numberKey": "1307"
        },
        {
            "key": "MM",
            "_countryCode": "95",
            "_firstCode": "M",
            "_gArea": "23",
            "_gContinent": "2",
            "_mnemonic": "MD",
            "_name": "缅甸",
            "_nameGeo": "Myanmar",
            "_numberKey": "1323"
        },
        {
            "key": "MN",
            "_countryCode": "976",
            "_firstCode": "M",
            "_gArea": "21",
            "_gContinent": "2",
            "_mnemonic": "MGG",
            "_name": "蒙古国",
            "_nameGeo": "Mongolia",
            "_numberKey": "1318"
        },
        {
            "key": "MO",
            "_countryCode": "853",
            "_firstCode": "A",
            "_gArea": "21",
            "_gContinent": "2",
            "_mnemonic": "AM",
            "_name": "澳门 [CN]",
            "_nameGeo": "",
            "_numberKey": "1301"
        },
        {
            "key": "MR",
            "_countryCode": "222",
            "_firstCode": "M",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "MLDNY",
            "_name": "毛里塔尼亚",
            "_nameGeo": "Mauritania",
            "_numberKey": "1312"
        },
        {
            "key": "MT",
            "_countryCode": "356",
            "_firstCode": "M",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "MET",
            "_name": "马耳他",
            "_nameGeo": "Malta",
            "_numberKey": "1308"
        },
        {
            "key": "MU",
            "_countryCode": "230",
            "_firstCode": "M",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "MLQS",
            "_name": "毛里求斯",
            "_nameGeo": "Mauritius",
            "_numberKey": "1313"
        },
        {
            "key": "MV",
            "_countryCode": "960",
            "_firstCode": "M",
            "_gArea": "22",
            "_gContinent": "2",
            "_mnemonic": "MEDF",
            "_name": "马尔代夫",
            "_nameGeo": "",
            "_numberKey": "1306"
        },
        {
            "key": "MW",
            "_countryCode": "265",
            "_firstCode": "M",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "MLW",
            "_name": "马拉维",
            "_nameGeo": "Malawi",
            "_numberKey": "1304"
        },
        {
            "key": "MX",
            "_countryCode": "52",
            "_firstCode": "M",
            "_gArea": "00",
            "_gContinent": "0",
            "_mnemonic": "MXG",
            "_name": "墨西哥",
            "_nameGeo": "Mexico",
            "_numberKey": "1314"
        },
        {
            "key": "MY",
            "_countryCode": "60",
            "_firstCode": "M",
            "_gArea": "23",
            "_gContinent": "2",
            "_mnemonic": "MLXY",
            "_name": "马来西亚",
            "_nameGeo": "Malaysia",
            "_numberKey": "1305"
        },
        {
            "key": "MZ",
            "_countryCode": "258",
            "_firstCode": "M",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "MSBK",
            "_name": "莫桑比克",
            "_nameGeo": "Mozambique",
            "_numberKey": "1322"
        },
        {
            "key": "NA",
            "_countryCode": "264",
            "_firstCode": "N",
            "_gArea": "32",
            "_gContinent": "3",
            "_mnemonic": "NMBY",
            "_name": "纳米比亚",
            "_nameGeo": "Namibia",
            "_numberKey": "1401"
        },
        {
            "key": "NC",
            "_countryCode": "687",
            "_firstCode": "X",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "XKLDNY",
            "_name": "新喀里多尼亚 [FR]",
            "_nameGeo": "New Caledonia",
            "_numberKey": "9702"
        },
        {
            "key": "NE",
            "_countryCode": "227",
            "_firstCode": "N",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "NRE",
            "_name": "尼日尔",
            "_nameGeo": "Niger",
            "_numberKey": "1409"
        },
        {
            "key": "NF",
            "_countryCode": "672",
            "_firstCode": "N",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "NFKD",
            "_name": "诺福克岛 [AU]",
            "_nameGeo": "",
            "_numberKey": "9502"
        },
        {
            "key": "NG",
            "_countryCode": "234",
            "_firstCode": "N",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "NRLY",
            "_name": "尼日利亚",
            "_nameGeo": "Nigeria",
            "_numberKey": "1410"
        },
        {
            "key": "NI",
            "_countryCode": "505",
            "_firstCode": "N",
            "_gArea": "01",
            "_gContinent": "0",
            "_mnemonic": "NJLG",
            "_name": "尼加拉瓜",
            "_nameGeo": "Nicaragua",
            "_numberKey": "1407"
        },
        {
            "key": "NL",
            "_countryCode": "31",
            "_firstCode": "H",
            "_gArea": "13",
            "_gContinent": "1",
            "_mnemonic": "HL",
            "_name": "荷兰",
            "_nameGeo": "Netherlands",
            "_numberKey": "1404"
        },
        {
            "key": "NO",
            "_countryCode": "47",
            "_firstCode": "N",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "NW",
            "_name": "挪威",
            "_nameGeo": "Norway",
            "_numberKey": "1408"
        },
        {
            "key": "NP",
            "_countryCode": "977",
            "_firstCode": "N",
            "_gArea": "22",
            "_gContinent": "2",
            "_mnemonic": "NBE",
            "_name": "尼泊尔",
            "_nameGeo": "Nepal",
            "_numberKey": "1403"
        },
        {
            "key": "NR",
            "_countryCode": "674",
            "_firstCode": "N",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "NL",
            "_name": "瑙鲁",
            "_nameGeo": "",
            "_numberKey": "1402"
        },
        {
            "key": "NZ",
            "_countryCode": "64",
            "_firstCode": "X",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "XXL",
            "_name": "新西兰",
            "_nameGeo": "New Zealand",
            "_numberKey": "1406"
        },
        {
            "key": "OM",
            "_countryCode": "968",
            "_firstCode": "A",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "AM",
            "_name": "阿曼",
            "_nameGeo": "Oman",
            "_numberKey": "1501"
        },
        {
            "key": "PA",
            "_countryCode": "507",
            "_firstCode": "B",
            "_gArea": "01",
            "_gContinent": "0",
            "_mnemonic": "BNM",
            "_name": "巴拿马",
            "_nameGeo": "Panama",
            "_numberKey": "1603"
        },
        {
            "key": "PE",
            "_countryCode": "51",
            "_firstCode": "B",
            "_gArea": "03",
            "_gContinent": "0",
            "_mnemonic": "BL",
            "_name": "秘鲁",
            "_nameGeo": "Peru",
            "_numberKey": "1606"
        },
        {
            "key": "PG",
            "_countryCode": "675",
            "_firstCode": "B",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "BBYXJNY",
            "_name": "巴布亚新几内亚",
            "_nameGeo": "Papua New Guinea",
            "_numberKey": "1604"
        },
        {
            "key": "PH",
            "_countryCode": "63",
            "_firstCode": "F",
            "_gArea": "23",
            "_gContinent": "2",
            "_mnemonic": "FLB",
            "_name": "菲律宾",
            "_nameGeo": "Philippines",
            "_numberKey": "1607"
        },
        {
            "key": "PK",
            "_countryCode": "92",
            "_firstCode": "B",
            "_gArea": "22",
            "_gContinent": "2",
            "_mnemonic": "BJST",
            "_name": "巴基斯坦",
            "_nameGeo": "Pakistan",
            "_numberKey": "1601"
        },
        {
            "key": "PL",
            "_countryCode": "48",
            "_firstCode": "B",
            "_gArea": "11",
            "_gContinent": "1",
            "_mnemonic": "BL",
            "_name": "波兰",
            "_nameGeo": "Poland",
            "_numberKey": "1608"
        },
        {
            "key": "PS",
            "_countryCode": "970",
            "_firstCode": "B",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "BLST",
            "_name": "巴勒斯坦",
            "_nameGeo": "Palestine",
            "_numberKey": "1602"
        },
        {
            "key": "PT",
            "_countryCode": "351",
            "_firstCode": "P",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "PTY",
            "_name": "葡萄牙",
            "_nameGeo": "Portugal",
            "_numberKey": "1610"
        },
        {
            "key": "PW",
            "_countryCode": "680",
            "_firstCode": "P",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "PL",
            "_name": "帕劳",
            "_nameGeo": "Palau",
            "_numberKey": "1614"
        },
        {
            "key": "PY",
            "_countryCode": "595",
            "_firstCode": "B",
            "_gArea": "03",
            "_gContinent": "0",
            "_mnemonic": "BLG",
            "_name": "巴拉圭",
            "_nameGeo": "Paraguay",
            "_numberKey": "1605"
        },
        {
            "key": "QA",
            "_countryCode": "974",
            "_firstCode": "K",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "KTE",
            "_name": "卡塔尔",
            "_nameGeo": "Qatar",
            "_numberKey": "1701"
        },
        {
            "key": "RO",
            "_countryCode": "40",
            "_firstCode": "L",
            "_gArea": "11",
            "_gContinent": "1",
            "_mnemonic": "LMNY",
            "_name": "罗马尼亚",
            "_nameGeo": "Romania",
            "_numberKey": "1802"
        },
        {
            "key": "RS",
            "_countryCode": "381",
            "_firstCode": "S",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "SEWY",
            "_name": "塞尔维亚",
            "_nameGeo": "Serbia",
            "_numberKey": "1909"
        },
        {
            "key": "RU",
            "_countryCode": "7",
            "_firstCode": "E",
            "_gArea": "11",
            "_gContinent": "1",
            "_mnemonic": "ELS",
            "_name": "俄罗斯联邦",
            "_nameGeo": "Russia",
            "_numberKey": "1803"
        },
        {
            "key": "RW",
            "_countryCode": "250",
            "_firstCode": "L",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "LWD",
            "_name": "卢旺达",
            "_nameGeo": "Rwanda",
            "_numberKey": "1804"
        },
        {
            "key": "SA",
            "_countryCode": "966",
            "_firstCode": "S",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "STALB",
            "_name": "沙特阿拉伯",
            "_nameGeo": "Saudi Arabia",
            "_numberKey": "1907"
        },
        {
            "key": "SB",
            "_countryCode": "677",
            "_firstCode": "S",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "SLMQD",
            "_name": "所罗门群岛",
            "_nameGeo": "Solomon Is.",
            "_numberKey": "1916"
        },
        {
            "key": "SC",
            "_countryCode": "248",
            "_firstCode": "S",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "SSE",
            "_name": "塞舌尔",
            "_nameGeo": "Seychelles",
            "_numberKey": "1911"
        },
        {
            "key": "SD",
            "_countryCode": "249",
            "_firstCode": "S",
            "_gArea": "35",
            "_gContinent": "3",
            "_mnemonic": "SD",
            "_name": "苏丹",
            "_nameGeo": "Sudan",
            "_numberKey": "1920"
        },
        {
            "key": "SE",
            "_countryCode": "46",
            "_firstCode": "R",
            "_gArea": "14",
            "_gContinent": "1",
            "_mnemonic": "RD",
            "_name": "瑞典",
            "_nameGeo": "Sweden",
            "_numberKey": "1924"
        },
        {
            "key": "SG",
            "_countryCode": "65",
            "_firstCode": "X",
            "_gArea": "23",
            "_gContinent": "2",
            "_mnemonic": "XJP",
            "_name": "新加坡",
            "_nameGeo": "Singapore",
            "_numberKey": "1913"
        },
        {
            "key": "SH",
            "_countryCode": "290",
            "_firstCode": "S",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "SHLND",
            "_name": "圣赫勒拿岛 [GB]",
            "_nameGeo": "Saint Helena",
            "_numberKey": "9008"
        },
        {
            "key": "SI",
            "_countryCode": "386",
            "_firstCode": "S",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "SLWNY",
            "_name": "斯洛文尼亚",
            "_nameGeo": "Slovenia",
            "_numberKey": "1915"
        },
        {
            "key": "SK",
            "_countryCode": "421",
            "_firstCode": "S",
            "_gArea": "11",
            "_gContinent": "1",
            "_mnemonic": "SLFK",
            "_name": "斯洛伐克",
            "_nameGeo": "Slovakia",
            "_numberKey": "1914"
        },
        {
            "key": "SL",
            "_countryCode": "232",
            "_firstCode": "S",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "SLLA",
            "_name": "塞拉利昂",
            "_nameGeo": "Sierra Leone",
            "_numberKey": "1912"
        },
        {
            "key": "SM",
            "_countryCode": "378",
            "_firstCode": "S",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "SMLN",
            "_name": "圣马力诺",
            "_nameGeo": "",
            "_numberKey": "1905"
        },
        {
            "key": "SN",
            "_countryCode": "221",
            "_firstCode": "S",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "SNJE",
            "_name": "塞内加尔",
            "_nameGeo": "Senegal",
            "_numberKey": "1908"
        },
        {
            "key": "SO",
            "_countryCode": "252",
            "_firstCode": "S",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "SML",
            "_name": "索马里",
            "_nameGeo": "Somalia",
            "_numberKey": "1929"
        },
        {
            "key": "SR",
            "_countryCode": "597",
            "_firstCode": "S",
            "_gArea": "03",
            "_gContinent": "0",
            "_mnemonic": "SLN",
            "_name": "苏里南",
            "_nameGeo": "Suriname",
            "_numberKey": "1921"
        },
        {
            "key": "ST",
            "_countryCode": "239",
            "_firstCode": "S",
            "_gArea": "33",
            "_gContinent": "3",
            "_mnemonic": "SDMHPLXB",
            "_name": "圣多美和普林西比",
            "_nameGeo": "São Tomé and Principe",
            "_numberKey": "1906"
        },
        {
            "key": "SV",
            "_countryCode": "503",
            "_firstCode": "S",
            "_gArea": "01",
            "_gContinent": "0",
            "_mnemonic": "SEWD",
            "_name": "萨尔瓦多",
            "_nameGeo": "El Salvador",
            "_numberKey": "1903"
        },
        {
            "key": "SY",
            "_countryCode": "963",
            "_firstCode": "X",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "XLY",
            "_name": "叙利亚",
            "_nameGeo": "Syria",
            "_numberKey": "1926"
        },
        {
            "key": "SZ",
            "_countryCode": "268",
            "_firstCode": "S",
            "_gArea": "32",
            "_gContinent": "3",
            "_mnemonic": "SWSL",
            "_name": "斯威士兰",
            "_nameGeo": "Swaziland",
            "_numberKey": "1923"
        },
        {
            "key": "TD",
            "_countryCode": "235",
            "_firstCode": "Z",
            "_gArea": "33",
            "_gContinent": "3",
            "_mnemonic": "ZD",
            "_name": "乍得",
            "_nameGeo": "Chad",
            "_numberKey": "0323"
        },
        {
            "key": "TG",
            "_countryCode": "228",
            "_firstCode": "D",
            "_gArea": "34",
            "_gContinent": "3",
            "_mnemonic": "DG",
            "_name": "多哥",
            "_nameGeo": "Togo",
            "_numberKey": "2005"
        },
        {
            "key": "TH",
            "_countryCode": "66",
            "_firstCode": "T",
            "_gArea": "23",
            "_gContinent": "2",
            "_mnemonic": "TG",
            "_name": "泰国",
            "_nameGeo": "Thailand",
            "_numberKey": "2004"
        },
        {
            "key": "TJ",
            "_countryCode": "992",
            "_firstCode": "T",
            "_gArea": "24",
            "_gContinent": "2",
            "_mnemonic": "TJKST",
            "_name": "塔吉克斯坦",
            "_nameGeo": "Tajikistan",
            "_numberKey": "2002"
        },
        {
            "key": "TL",
            "_countryCode": "670",
            "_firstCode": "D",
            "_gArea": "23",
            "_gContinent": "2",
            "_mnemonic": "DDW",
            "_name": "东帝汶",
            "_nameGeo": "Timor-Leste",
            "_numberKey": "0508"
        },
        {
            "key": "TM",
            "_countryCode": "993",
            "_firstCode": "T",
            "_gArea": "24",
            "_gContinent": "2",
            "_mnemonic": "TKMST",
            "_name": "土库曼斯坦",
            "_nameGeo": "Turkmenistan",
            "_numberKey": "2012"
        },
        {
            "key": "TN",
            "_countryCode": "216",
            "_firstCode": "T",
            "_gArea": "35",
            "_gContinent": "3",
            "_mnemonic": "TNS",
            "_name": "突尼斯",
            "_nameGeo": "Tunisia",
            "_numberKey": "2010"
        },
        {
            "key": "TO",
            "_countryCode": "676",
            "_firstCode": "T",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "TJ",
            "_name": "汤加",
            "_nameGeo": "Tonga",
            "_numberKey": "2006"
        },
        {
            "key": "TR",
            "_countryCode": "90",
            "_firstCode": "T",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "TEJ",
            "_name": "土耳其",
            "_nameGeo": "Turkey",
            "_numberKey": "2011"
        },
        {
            "key": "TT",
            "_countryCode": "1-868",
            "_firstCode": "T",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "TLNDHDBG",
            "_name": "特立尼达和多巴哥",
            "_nameGeo": "Trinidad and Tobago",
            "_numberKey": "2007"
        },
        {
            "key": "TV",
            "_countryCode": "688",
            "_firstCode": "T",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "TWL",
            "_name": "图瓦卢",
            "_nameGeo": "",
            "_numberKey": "2009"
        },
        {
            "key": "TW",
            "_countryCode": "886",
            "_firstCode": "T",
            "_gArea": "21",
            "_gContinent": "2",
            "_mnemonic": "TW",
            "_name": "台湾 [CN]",
            "_nameGeo": "",
            "_numberKey": "2001"
        },
        {
            "key": "TZ",
            "_countryCode": "255",
            "_firstCode": "T",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "TSNY",
            "_name": "坦桑尼亚",
            "_nameGeo": "Tanzania",
            "_numberKey": "2003"
        },
        {
            "key": "UA",
            "_countryCode": "380",
            "_firstCode": "W",
            "_gArea": "11",
            "_gContinent": "1",
            "_mnemonic": "WKL",
            "_name": "乌克兰",
            "_nameGeo": "Ukraine",
            "_numberKey": "2102"
        },
        {
            "key": "UG",
            "_countryCode": "256",
            "_firstCode": "W",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "WGD",
            "_name": "乌干达",
            "_nameGeo": "Uganda",
            "_numberKey": "2101"
        },
        {
            "key": "US",
            "_countryCode": "1",
            "_firstCode": "M",
            "_gArea": "00",
            "_gContinent": "0",
            "_mnemonic": "MG",
            "_name": "美国",
            "_nameGeo": "United States",
            "_numberKey": "2105"
        },
        {
            "key": "UY",
            "_countryCode": "598",
            "_firstCode": "W",
            "_gArea": "03",
            "_gContinent": "0",
            "_mnemonic": "WLG",
            "_name": "乌拉圭",
            "_nameGeo": "Uruguay",
            "_numberKey": "2104"
        },
        {
            "key": "UZ",
            "_countryCode": "998",
            "_firstCode": "W",
            "_gArea": "24",
            "_gContinent": "2",
            "_mnemonic": "WCBKST",
            "_name": "乌兹别克斯坦",
            "_nameGeo": "Uzbekistan",
            "_numberKey": "2103"
        },
        {
            "key": "VA",
            "_countryCode": "379",
            "_firstCode": "F",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "FDG",
            "_name": "梵蒂冈",
            "_nameGeo": "",
            "_numberKey": "2205"
        },
        {
            "key": "VC",
            "_countryCode": "1-784",
            "_firstCode": "S",
            "_gArea": "02",
            "_gContinent": "0",
            "_mnemonic": "SWSTHGLNDS",
            "_name": "圣文森特和格林纳丁斯",
            "_nameGeo": "St. Vin. and Gren.",
            "_numberKey": "1902"
        },
        {
            "key": "VE",
            "_countryCode": "58",
            "_firstCode": "W",
            "_gArea": "03",
            "_gContinent": "0",
            "_mnemonic": "WNRL",
            "_name": "委内瑞拉",
            "_nameGeo": "Venezuela",
            "_numberKey": "2203"
        },
        {
            "key": "VN",
            "_countryCode": "84",
            "_firstCode": "Y",
            "_gArea": "23",
            "_gContinent": "2",
            "_mnemonic": "YN",
            "_name": "越南",
            "_nameGeo": "Vietnam",
            "_numberKey": "2204"
        },
        {
            "key": "VU",
            "_countryCode": "678",
            "_firstCode": "W",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "WNAT",
            "_name": "瓦努阿图",
            "_nameGeo": "Vanuatu",
            "_numberKey": "2202"
        },
        {
            "key": "WS",
            "_countryCode": "685",
            "_firstCode": "X",
            "_gArea": "41",
            "_gContinent": "4",
            "_mnemonic": "XSMY",
            "_name": "萨摩亚",
            "_nameGeo": "Samoa",
            "_numberKey": "1928"
        },
        {
            "key": "XK",
            "_countryCode": "383",
            "_firstCode": "K",
            "_gArea": "12",
            "_gContinent": "1",
            "_mnemonic": "KSW",
            "_name": "科索沃",
            "_nameGeo": "",
            "_numberKey": "1107"
        },
        {
            "key": "YE",
            "_countryCode": "967",
            "_firstCode": "Y",
            "_gArea": "25",
            "_gContinent": "2",
            "_mnemonic": "YM",
            "_name": "也门",
            "_nameGeo": "Yemen",
            "_numberKey": "2501"
        },
        {
            "key": "ZA",
            "_countryCode": "27",
            "_firstCode": "N",
            "_gArea": "32",
            "_gContinent": "3",
            "_mnemonic": "NF",
            "_name": "南非",
            "_nameGeo": "South Africa",
            "_numberKey": "1917"
        },
        {
            "key": "ZM",
            "_countryCode": "260",
            "_firstCode": "Z",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "ZBY",
            "_name": "赞比亚",
            "_nameGeo": "Zambia",
            "_numberKey": "2601"
        },
        {
            "key": "ZW",
            "_countryCode": "263",
            "_firstCode": "J",
            "_gArea": "31",
            "_gContinent": "3",
            "_mnemonic": "JBBW",
            "_name": "津巴布韦",
            "_nameGeo": "Zimbabwe",
            "_numberKey": "2602"
        }
    ],
    "Logistics_code": [
        {
            "key": "Arrived",
            "_code": "25",
            "_color": "2962ff",
            "_desc": "您的货物已经到达目的国机场。",
            "_name": "到达目的",
            "_order": "04"
        },
        {
            "key": "Booked",
            "_code": "10",
            "_color": "00bcd4",
            "_desc": "您的货物已订舱。",
            "_name": "订舱",
            "_order": "01"
        },
        {
            "key": "Delivered",
            "_code": "40",
            "_color": "43a047",
            "_desc": "您的货物已经被成功取走。",
            "_name": "取货成功",
            "_order": "06"
        },
        {
            "key": "InTransit",
            "_code": "20",
            "_color": "2196f3",
            "_desc": "您的货物正在运输途中。",
            "_name": "运输途中",
            "_order": "03"
        },
        {
            "key": "NotFound",
            "_code": "00",
            "_color": "757575",
            "_desc": "您的货物查询不到跟踪信息。",
            "_name": "查询不到",
            "_order": "07"
        },
        {
            "key": "Notified",
            "_code": "30",
            "_color": "0d47a1",
            "_desc": "您的货物已到达目的地，已通知收货人取货。",
            "_name": "取货通知",
            "_order": "05"
        },
        {
            "key": "Received",
            "_code": "15",
            "_color": "00b8ff",
            "_desc": "您的货物已被航司接收。",
            "_name": "收到货物",
            "_order": "02"
        }
    ]
}